version: '2'

networks:
  local-proxy:
    external: true

services:

  wordpress:
    image: wordpress
    networks:
      - local-proxy
    links:
      - db:mysql
    ports:
      - 9090:80
    environment:
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: marthafund
      WORDPRESS_DB_NAME: marthafund
      VIRTUAL_HOST: martha.docker
      VIRTUAL_PORT: 80
    volumes:
      - ./wp-content/themes/martha:/var/www/html/wp-content/themes/martha

  db:
    image: mariadb
    networks:
      - local-proxy
    environment:
      MYSQL_ROOT_PASSWORD: marthafund
    volumes:
      - ./db:/var/lib/mysql
