version: '2'
volumes:
  mysql:
    driver: local
services:

  wordpress:
    image: wordpress
    links:
      - db:mysql
    ports:
      - 9090:80
    environment:
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: marthafund
      WORDPRESS_DB_NAME: marthafund
    volumes:
      - ./wp-content/themes/martha:/var/www/html/wp-content/themes/martha

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: marthafund
    volumes:
      - mysql:/var/lib/mysql
